swagger: '2.0'
info:
  description: >-
    This contains common definitions required for creating Swagger API specification file.
  version: '1'
  title: Common definitions for Swagger API specification
  license:
    name: 'Copyright © 2017 VMware, Inc. All Rights Reserved.'
definitions:
  BaseExceptionModel:
    type: object
    description: Represents the exception object thrown from API
    x-ignore: true    
    properties:
      errorCode:
        description: Application error code specific to operation
        type: integer
        format: int32
      message:
        description: Friendly error message (any serializable type)
        type: object
      activityId:
        description: TransactionId of the request in Guid format
        type: string
        format: uuid

  BaseModel:
    type: object
    description: Parent class of all view models used in API
    x-ignore: true
    properties:
      id:
        description: Identifier of the resource in integer format
        type: integer
        format: int32
      uuid:
        description: Identifier of the resource in Guid format
        type: string
        format: uuid
